export const UPDATE_BANNER = "UPDATE_BANNER";
export const UPDATE_CODE = "UPDATE_CODE";
// Animations
export const START_BUTTON_REVEAL = "START_BUTTON_REVEAL";
export const FINISH_BUTTON_REVEAL = "FINISH_BUTTON_REVEAL";

export const START_BUTTON_HIDE = "START_BUTTON_HIDE";
export const FINISH_BUTTON_HIDE = "FINISH_BUTTON_HIDE";

export const START_KEY_DROP = "START_KEY_DROP";
export const FINISH_KEY_DROP = "FINISH_KEY_DROP";

export const PICK_KEY_UP = "PICK_KEY_UP";
export const SET_KEY_DOWN = "SET_KEY_DOWN";

export const START_OPEN_BOX = "START_OPEN_BOX";
export const FINISH_OPEN_BOX = "FINISH_OPEN_BOX";
